{{-- <!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>

<body style="font-family:Arial;background:#f5f5f5;padding:40px">

<div style="max-width:600px;margin:auto;background:white;padding:30px;border-radius:10px">

<h2 style="color:#4f46e5">Welcome to EdFlow 🎓</h2>

<p>Hello <b>{{ $data['name'] }}</b>,</p>

<p>Your student account has been created successfully.</p>

<h3>Account Details</h3>

<ul>
<li><b>Name:</b> {{ $data['name'] }}</li>
<li><b>Email:</b> {{ $data['email'] }}</li>
<li><b>Password:</b> {{ $data['password'] }}</li>
<li><b>Roll Number:</b> {{ $data['roll_number'] }}</li>
<li><b>Course:</b> {{ $data['course_name'] }}</li>
</ul>

<p>Please login to the system.</p>
<a href="{{ url('/login') }}"
style="background:#4f46e5;color:white;padding:12px 20px;border-radius:6px;text-decoration:none;">
Login to EdFlow
</a>

</div>

</body>
</html> --}}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to EdFlow</title>
    <style>
        /* Base resets for email clients */
        body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
        table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
        img { -ms-interpolation-mode: bicubic; }
        img { border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; }
        table { border-collapse: collapse !important; }
        body { height: 100% !important; margin: 0 !important; padding: 0 !important; width: 100% !important; }
        a[x-apple-data-detectors] { color: inherit !important; text-decoration: none !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; line-height: inherit !important; }
    </style>
</head>
<body style="background-color: #F3F4F6; margin: 0 !important; padding: 0 !important; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">

    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: #F3F4F6; padding: 40px 20px;">
        <tr>
            <td align="center">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.05);">
                    
                    <tr>
                        <td align="center" style="background-color: #4F46E5; padding: 40px 20px;">
                            <h1 style="color: #ffffff; font-size: 28px; margin: 0; font-weight: 700; letter-spacing: 0.5px;">
                                Welcome to EdFlow 🎓
                            </h1>
                            <p style="color: #E0E7FF; font-size: 16px; margin: 10px 0 0 0; font-weight: 400;">
                                Your academic journey starts here.
                            </p>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding: 40px 30px;">
                            <p style="color: #374151; font-size: 16px; line-height: 24px; margin: 0 0 20px 0;">
                                Hello <strong>{{ $data['name'] }}</strong>,
                            </p>
                            <p style="color: #4B5563; font-size: 16px; line-height: 24px; margin: 0 0 30px 0;">
                                Your official student account has been successfully generated by the administration. You can now access your academic portal to view your enrolled courses, track attendance, and monitor your performance.
                            </p>

                            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: #F9FAFB; border: 1px solid #E5E7EB; border-radius: 8px;">
                                <tr>
                                    <td style="padding: 25px;">
                                        <h3 style="color: #111827; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; margin: 0 0 15px 0; border-bottom: 1px solid #E5E7EB; padding-bottom: 10px;">
                                            Your Login Credentials
                                        </h3>
                                        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="font-size: 15px; line-height: 28px;">
                                            <tr>
                                                <td width="35%" style="color: #6B7280; font-weight: 600;">Full Name:</td>
                                                <td width="65%" style="color: #111827; font-weight: 600;">{{ $data['name'] }}</td>
                                            </tr>
                                            <tr>
                                                <td style="color: #6B7280; font-weight: 600;">Roll Number:</td>
                                                <td style="color: #111827; font-weight: 600;">{{ $data['roll_number'] }}</td>
                                            </tr>
                                            <tr>
                                                <td style="color: #6B7280; font-weight: 600;">Course:</td>
                                                <td style="color: #111827; font-weight: 600;">{{ $data['course_name'] }}</td>
                                            </tr>
                                            <tr>
                                                <td style="color: #6B7280; font-weight: 600;">Email:</td>
                                                <td style="color: #4F46E5; font-weight: 600;">{{ $data['email'] }}</td>
                                            </tr>
                                            <tr>
                                                <td style="color: #6B7280; font-weight: 600; padding-top: 8px;">Password:</td>
                                                <td style="padding-top: 8px;">
                                                    <span style="background-color: #E0E7FF; color: #4338CA; padding: 6px 12px; border-radius: 6px; font-family: 'Courier New', Courier, monospace; font-size: 16px; font-weight: bold; letter-spacing: 1.5px;">
                                                        {{ $data['password'] }}
                                                    </span>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>

                            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="margin-top: 25px;">
                                <tr>
                                    <td align="center" style="background-color: #FEF2F2; padding: 12px; border-radius: 6px; border: 1px solid #FEE2E2;">
                                        <p style="color: #DC2626; font-size: 13px; font-weight: 600; margin: 0;">
                                            🔒 For your security, please change your password immediately after your first login.
                                        </p>
                                    </td>
                                </tr>
                            </table>

                            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="margin-top: 35px;">
                                <tr>
                                    <td align="center">
                                        <a href="{{ url('/login') }}" style="display: inline-block; background-color: #4F46E5; color: #ffffff; font-size: 16px; font-weight: bold; text-decoration: none; padding: 14px 35px; border-radius: 8px; box-shadow: 0 4px 6px rgba(79, 70, 229, 0.25);">
                                            Access Student Portal
                                        </a>
                                    </td>
                                </tr>
                            </table>

                        </td>
                    </tr>

                    <tr>
                        <td align="center" style="background-color: #F9FAFB; padding: 25px 30px; border-top: 1px solid #E5E7EB;">
                            <p style="color: #4B5563; font-size: 14px; margin: 0 0 5px 0;">
                                Best regards,<br><strong>EdFlow Administration</strong>
                            </p>
                            <p style="color: #9CA3AF; font-size: 12px; margin: 15px 0 0 0; line-height: 18px;">
                                This is an automated system email generated by EdFlow. Please do not reply directly to this message. If you require assistance, please contact the IT department.
                            </p>
                        </td>
                    </tr>
                </table>
                
                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                    <tr><td height="40"></td></tr>
                </table>
            </td>
        </tr>
    </table>

</body>
</html>